### ISSUE TITLE
Using Tools or Recording not working

### ISSUE THREAD

**Issue by CKettle** [open-rpa/openrpa#148]
I would like to test the tool out, maybe im missing a prerequisite after i downloaded and tried to record actions then this error message popped up.
![Error](https://user-images.githubusercontent.com/57894905/69225908-f0ffae00-0b87-11ea-989c-e63a106d6ccb.JPG)

I also used the Updated but that didnt solve the issue.

**Comment by skadefro** [comment]
The error message is missing from the screenshot.
Can you get the top part as well, or find the error in the log tab?

**Comment by CKettle** [comment]
This is what i got in the Logs:

[11:36:19.674][Error] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OpenRPA.MainWindow.StopRecordPlugins()
   at OpenRPA.MainWindow.onCancel()
   at OpenRPA.Input.InputDriver.CancelEventHandler.Invoke()
   at OpenRPA.Input.InputDriver.<initCancelKey>b__77_0(IDetectorPlugin plugin, IDetectorEvent detector, EventArgs e)
[11:36:19.606][Error] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OpenRPA.MainWindow.StartRecordPlugins()
   at OpenRPA.MainWindow.onRecord(Object _item)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Ribbon.RibbonButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by skadefro** [comment]
Ah ... Yes, that can be a little tricky 
In order to record you **need** to select an sequence first. 
Do you have a sequence in your workflow ? 
![image](https://user-images.githubusercontent.com/4155937/69227365-feb23500-0b81-11ea-8a7c-f661c28ded39.png)
If not, then go to the toolbox and search for Sequence and then drag on on to the designer
![image](https://user-images.githubusercontent.com/4155937/69227456-1c7f9a00-0b82-11ea-965b-f187acb626e8.png)
Then make sure its selected before recording ( the bar should be yellow, and the "grey" like in my first picture  )
![image](https://user-images.githubusercontent.com/4155937/69227506-328d5a80-0b82-11ea-85e3-c38cfcb3b7c0.png)
Does this help and solve the issue ?

**Comment by CKettle** [comment]
its basically the same error when trying to using open an application when i click "Open Selector", the same error also happens when i click record even when the sequence is selected.

**Comment by skadefro** [comment]
That must be another error then, clicking select on in OpenApplication will never try and locate an sequence, what error do you get when you click Select ?

If it helps we can try an remote session using google meet or teamviewer and you can show me the error ?

**Comment by CKettle** [comment]
It looks like same error as i attached above. We can use teamviewer if you want to see it in detail.

**Comment by skadefro** [comment]
if you get it from this link ( it works even if you have teamviewer already installed ) then we don't need to exchange id's and code's
https://get.teamviewer.com/openrpa

**Comment by skadefro** [comment]
So the problem was dll's being blocked.
I will try and make an installer so this doesn't keep being a problem, but i have other things i need to complete first.
