### ISSUE TITLE
System.IO.IOException: The directory is not empty

### ISSUE THREAD

**Issue by anomula01** [open-rpa/openrpa#280]
Hi,

Following message is being repeatable logged, also the message is referring to a non-existant directory (C:\code\openrpa\OpenRPA):

[21:58:33.423][Error] System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at OpenRPA.MainWindow.<>c__DisplayClass58_1.<LoadServerData>b__4(Project p) in C:\code\openrpa\OpenRPA\MainWindow.xaml.cs:line 931

**Comment by skadefro** [comment]
The robot is trying to remove a project that no longer exists, but there is still files in the folder.
Delete all folders under "documents\openrpa", the robot will just download all projects and workflows, again.

**Comment by anomula01** [comment]
Thanks Allan for your quick response.  After deleting the all the folders the error went away. However, now I am seeing following error in the log: Please advise.

[08:43:07.103][Error] System.DllNotFoundException: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at OpenRPA.Script.Plugin.Initialize(IOpenRPAClient client)
   at OpenRPA.Interfaces.Plugins.LoadPlugins(IOpenRPAClient client, String projectsDirectory)

**Comment by skadefro** [comment]
That is only an error, if you have python installed and expect it to work.
If not, you can safely ignore it
