### ISSUE TITLE
System.IO.IOException: "The process cannot access the file" while issuing jwt token.

### ISSUE THREAD

**Issue by tomleetv** [open-rpa/openrpa#346]
**Describe the bug**

Hello. I am using OpenRPA as an automation tool for my project. Thanks for developing this good application btw.

System.IO.IOException is occured when issuing new jwt token

Exception information is here below.

System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\Users\tomlee\Documents\OpenRPA\settings.json' because it is being used by another process.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at OpenRPA.AppSettings`1.Save(String fileName) in C:\code\openrpa\OpenRPA.Interfaces\AppSettings.cs:line 14

**To Reproduce**
1. Go to settings.json file and open it with notepad. (C:\Users\tomlee\Documents\OpenRPA\settings.json)
2. Deleting username and jwt value (e.g. "username": "", "jwt": "" )
2. execute OpenRPA.exe
3. the exception is occured.
4. See error in Logging window.

**Expected behavior**
no exception

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version [1.0.135.0]

**Workflow (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by skadefro** [comment]
You have the settings file open in another application that has a lock on the file
Close the application, so OpenRPA can update it's settings file

**Comment by tomleetv** [comment]
Hello. skadefro.

Thanks for the comment.

I didn't open the setting file in another application.

but I don't understand this problem clearly. even I made break point using Visual Studio I look this problem step by step. 

This exception doesn't make crash to OpenRPA Application. So If your opinion is O.K. I will not bother you :)

**Comment by skadefro** [comment]
You are not bothering me, but i need a way to reproduce this, if you think its bug in the product.

**Comment by tomleetv** [comment]
I think this is not critical issue. I reported this for just in case. I will check my OpenFlow server if I found serious issue about this I will reissue this again :) thanks!
